---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: build
  image: golang:1.13-alpine
  commands:
    - apk --no-cache add git
    - go get -u github.com/go-bindata/go-bindata/...
    - go get -d ./...
    - go-bindata -nomemcopy -fs -prefix "./static" $$(find ./static -type f -name '*.css' -or -name '*.js') $$(find ./templates -type f)
    - CGO_ENABLED=0 go build -a -tags netgo -ldflags '-w' -o collatz collatz.go bindata.go

- name: docker
  image: plugins/docker
  settings:
    username: michiel
    password:
      from_secret: docker_password
    repo: docker.webmichiel.nl/collatz-explorer/collatz-explorer
    registry: docker.webmichiel.nl
    auto_tag: true
  when:
    event:
    - tag

image_pull_secrets:
- dockerconfig
